coder/coder-desktop-windows

- App/Converters/AgentStatusToColorConverter.cs
- App/ViewModels/AgentViewModel.cs
- App/ViewModels/TrayWindowViewModel.cs
On the Mac app, we use Yellow when an agent's last handshake was longer than 5 minutes ago. We should reserve red for a more fatal error, rather than something that will show on every connection.
> chore: change stale agent colour to yellow

- .gitattributes
- Coder.Desktop.sln
- MutagenSdk/MutagenClient.cs
- MutagenSdk/MutagenSdk.csproj
- MutagenSdk/NamedPipesConnectionFactory.cs
- MutagenSdk/Proto/filesystem/behavior/probe_mode.proto
- MutagenSdk/Proto/selection/selection.proto
- MutagenSdk/Proto/service/synchronization/synchronization.proto
- MutagenSdk/Proto/synchronization/compression/algorithm.proto
- MutagenSdk/Proto/synchronization/configuration.proto
- MutagenSdk/Proto/synchronization/core/change.proto
- MutagenSdk/Proto/synchronization/core/conflict.proto
- MutagenSdk/Proto/synchronization/core/entry.proto
- MutagenSdk/Proto/synchronization/core/ignore/ignore_vcs_mode.proto
- MutagenSdk/Proto/synchronization/core/ignore/syntax.proto
- MutagenSdk/Proto/synchronization/core/mode.proto
- MutagenSdk/Proto/synchronization/core/permissions_mode.proto
- MutagenSdk/Proto/synchronization/core/problem.proto
- MutagenSdk/Proto/synchronization/core/symbolic_link_mode.proto
- MutagenSdk/Proto/synchronization/hashing/algorithm.proto
- MutagenSdk/Proto/synchronization/rsync/receive.proto
- MutagenSdk/Proto/synchronization/scan_mode.proto
- MutagenSdk/Proto/synchronization/session.proto
- MutagenSdk/Proto/synchronization/stage_mode.proto
- MutagenSdk/Proto/synchronization/state.proto
- MutagenSdk/Proto/synchronization/version.proto
- MutagenSdk/Proto/synchronization/watch_mode.proto
- MutagenSdk/Proto/url/url.proto
- MutagenSdk/Update-Proto.ps1
- MutagenSdk/packages.lock.json
Contains a gRPC client for mutagen's synchronization API.
All required .proto files are vendored using a new script `Update-Proto.ps1`, which finds all required files by scanning `import` directives.
The vendored files are modified to add `csharp_namespace` and a MIT license header from mutagen.
Example usage:
```cs
using var client = new MutagenClient(@"C:\Users\dean\.mutagen");
var res = await client.Synchronization.ListAsync(new ListRequest
{
Selection = new Selection
{
All = true,
},
});
foreach (var state in res.SessionStates)
Console.WriteLine(state);
```
Close https://github.com/coder/internal/issues/378
> chore: add MutagenSdk project

- scripts/Publish.ps1
- scripts/files/.gitignore
`Publish.ps1` now downloads (if unmodified) the necessary mutagen files from our GCS bucket. These files aren't checked into the repo since they are large, but they will be cached and ignored in the workdir.
`mutagen.exe` and `mutagen-agents.tar.gz` will appear in the same directory as `wintun.dll` in the install.
```powershell
PS C:\Users\dean\git\coder-desktop-windows> ls .\publish\buildtemp-1.2.3.4-x64\vpn
Directory: C:\Users\dean\git\coder-desktop-windows\publish\buildtemp-1.2.3.4-x64\vpn
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         1/03/2025     12:02           5431 LICENSE.WINTUN.txt
-a----        10/03/2025     11:58       17964207 mutagen-agents.tar.gz
-a----        10/03/2025     11:58       13797376 …
```
> feat: include mutagen binary in installer

- MutagenSdk/MutagenClient.cs
- MutagenSdk/Proto/filesystem/behavior/probe_mode.proto
- MutagenSdk/Proto/selection/selection.proto
- MutagenSdk/Proto/service/daemon/daemon.proto
- MutagenSdk/Proto/service/synchronization/synchronization.proto
- MutagenSdk/Proto/synchronization/compression/algorithm.proto
- MutagenSdk/Proto/synchronization/configuration.proto
- MutagenSdk/Proto/synchronization/core/change.proto
- MutagenSdk/Proto/synchronization/core/conflict.proto
- MutagenSdk/Proto/synchronization/core/entry.proto
- MutagenSdk/Proto/synchronization/core/ignore/ignore_vcs_mode.proto
- MutagenSdk/Proto/synchronization/core/ignore/syntax.proto
- MutagenSdk/Proto/synchronization/core/mode.proto
- MutagenSdk/Proto/synchronization/core/permissions_mode.proto
- MutagenSdk/Proto/synchronization/core/problem.proto
- MutagenSdk/Proto/synchronization/core/symbolic_link_mode.proto
- MutagenSdk/Proto/synchronization/rsync/receive.proto
- MutagenSdk/Proto/synchronization/scan_mode.proto
- MutagenSdk/Proto/synchronization/session.proto
- MutagenSdk/Proto/synchronization/stage_mode.proto
- MutagenSdk/Proto/synchronization/state.proto
- MutagenSdk/Proto/synchronization/version.proto
- MutagenSdk/Proto/synchronization/watch_mode.proto
- MutagenSdk/Proto/url/url.proto
- MutagenSdk/Update-Proto.ps1
- Adds support for an array of protobuf "entry points" in `Mutagen/Update-Proto.ps1`
- Also refactors file modification/writing to be more efficient and to not include an unnecessary byte order mark and two trailing new lines
- Adds Daemon service to `MutagenClient`
> feat: add daemon service to MutagenSdk

- App/Controls/SizedFrame.cs
- App/Views/SignInWindow.xaml
- App/Views/SignInWindow.xaml.cs
- App/Views/TrayWindow.xaml
- App/Views/TrayWindow.xaml.cs
First part of sign-in revamp.
Adds a `SizedFrame` to unify some of the quirky window sizing code, as it's now used in `SignInWindow` as well as `TrayWindow`.
It'll also be used in `FileSyncListWindow`
> chore: add SizedFrame for window sizing

- App/ViewModels/TrayWindowViewModel.cs
- App/Views/Pages/TrayWindowDisconnectedPage.xaml
- App/Views/Pages/TrayWindowLoadingPage.xaml
- App/Views/Pages/TrayWindowLoginRequiredPage.xaml
- App/Views/Pages/TrayWindowMainPage.xaml
Part of https://github.com/coder/internal/issues/458
> chore: rename CoderVPN to Coder Connect in UI

- App/App.csproj
- App/App.xaml.cs
- App/Services/MutagenController.cs
- App/packages.lock.json
- Installer/Program.cs
- Tests.App/Services/MutagenControllerTest.cs
- Tests.Vpn.Service/packages.lock.json
- Tests.Vpn/Tests.Vpn.csproj
- Tests.Vpn/packages.lock.json
- Vpn.DebugClient/Vpn.DebugClient.csproj
- Vpn.DebugClient/packages.lock.json
- Vpn.Service/packages.lock.json
- Vpn/RegistryConfigurationSource.cs
- Vpn/Vpn.csproj
- Vpn/packages.lock.json
- scripts/Get-Mutagen.ps1
- scripts/Publish.ps1
fixes coder/internal#380
Adds MutagenController service, which manages the lifecycle of the `mutagen` daemon and exposes methods to query and modify sync sessions.
Sync sessions themselves are a placeholder which will need to be filled out and plumbed thru to the actual API. This just handles daemon lifecycle for now.
> feat: adds mutagen daemon controller

- Installer/Program.cs
- scripts/Get-WindowsAppSdk.ps1
- scripts/Publish.ps1
- scripts/files/.gitignore
> added windows app sdk fetching and bundling into the installer

- App/App.xaml.cs
- App/Models/RpcModel.cs
- App/Models/SyncSessionControllerStateModel.cs
- App/Models/SyncSessionModel.cs
- App/Services/MutagenController.cs
- App/Services/RpcController.cs
- App/ViewModels/FileSyncListViewModel.cs
- App/ViewModels/SyncSessionViewModel.cs
- App/Views/Pages/FileSyncListMainPage.xaml
- App/Views/TrayWindow.xaml.cs
- MutagenSdk/MutagenClient.cs
- MutagenSdk/NamedPipesConnectionFactory.cs
- Tests.App/Services/MutagenControllerTest.cs
- Use locks during operations for daemon process consistency
- Use a state model for UI rendering
- Use events to signal state changes
- Fix some tooltip problems that arise from polling
> chore: rework mutagen controller, add polling

- App/App.xaml.cs
- App/Models/RpcModel.cs
- App/Models/SyncSessionControllerStateModel.cs
- App/Models/SyncSessionModel.cs
- App/Services/MutagenController.cs
- App/Services/RpcController.cs
- App/ViewModels/FileSyncListViewModel.cs
- App/ViewModels/SyncSessionViewModel.cs
- App/Views/FileSyncListWindow.xaml.cs
- App/Views/Pages/FileSyncListMainPage.xaml
- App/Views/Pages/TrayWindowMainPage.xaml
- App/Views/TrayWindow.xaml.cs
- MutagenSdk/MutagenClient.cs
- MutagenSdk/NamedPipesConnectionFactory.cs
- MutagenSdk/Proto/service/prompting/prompting.proto
- MutagenSdk/Update-Proto.ps1
- Tests.App/Services/MutagenControllerTest.cs
- Adds `PauseSyncSession` and `ResumeSyncSession`
- Adds `SyncSessionViewModel` that wraps `SyncSessionModel` and adds view methods (as you cannot access the parent context if you're in a `ItemsRepeater` apparently)
- Wires up Initialize, List, Pause, Resume, Terminate and Create in the file sync UI
- Prevent the app from loading until mutagen finishes initializing (either successfully or not) (in a different PR)
- Add reinitialization logic to mutagen controller (in a different PR)
Closes #26 
Closes #28 
Closes #29
> feat: wire up file sync window

- Tests.Vpn.Service/DownloaderTest.cs
- Vpn.Service/Downloader.cs
fixes #69
Fixes `Downloader` to remove the `DownloadTask` when it is done via a completion. This will allow changing Coder deployments, which use different URLs but whose files are downloaded to the same place.
> fix: fix downloading different URLs to same destination

- Tests.Vpn.Service/DownloaderTest.cs
- Vpn.Service/Downloader.cs
Respects the cancelation token provided to `StartDownloadAsync` even when there is another download already in progress to the same destination.
> feat: allow cancelation of download of a different URL

- App/Services/MutagenController.cs
- App/ViewModels/FileSyncListViewModel.cs
- App/Views/Pages/FileSyncListMainPage.xaml
- Tests.App/Services/MutagenControllerTest.cs
https://github.com/user-attachments/assets/96d57799-0db8-4146-a93c-c157645cb4e9
> feat: add create progress to file sync window

- Tests.Vpn.Service/DownloaderTest.cs
- Vpn.Service/Downloader.cs
Fixes https://github.com/coder/internal/issues/598
There is a possible race where if the cancellation token is expired, `Download()` never gets called and the tempFile is never disposed of (at least until GC). We also switch to synchronous IO so that a pending overlapped write won't block the deletion.
These issues can cause races in our tests when we try to clean up the directory.
> fix: fix Downloader to dispose tempFile and use synchronous IO 

- App/App.csproj
- App/App.xaml.cs
- App/packages.lock.json
- Installer/Installer.csproj
- Installer/Program.cs
- Tests.Vpn.Service/packages.lock.json
- Vpn.Service/ManagerConfig.cs
- Vpn.Service/Program.cs
- Vpn.Service/Vpn.Service.csproj
- Vpn.Service/packages.lock.json
Adds logging to the Coder Desktop application.
> feat: add logging to App

- App/Services/MutagenController.cs
Adds some logging to the mutagen controller.
> chore: add logging to mutagen controller

- App/App.xaml.cs
- App/Program.cs
- App/Services/UserNotifier.cs
Adds support for OS notifications, which I'll use to show errors handling URIs in a subsequent PR.
[Screen Recording 2025-05-01 145532.mp4 <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/tCz4CxRU9jhAJ7zH8RTi/f838fb8a-6815-48a7-bd52-63d6a06ce742.mp4" />](https://app.graphite.dev/media/video/tCz4CxRU9jhAJ7zH8RTi/f838fb8a-6815-48a7-bd52-63d6a06ce742.mp4)
> feat: add support for notifications

- App/Views/Pages/SignInTokenPage.xaml
- App/Views/Pages/SignInTokenPage.xaml.cs
- App/Views/Pages/SignInUrlPage.xaml
- App/Views/Pages/SignInUrlPage.xaml.cs
> feat: enter submits sign in information

- App/Services/UriHandler.cs
- Tests.App/Services/UriHandlerTest.cs
Fixes #52
Checks for the authority string, i.e. `coder.example.com` in `coder://coder.example.com/v0/open/...` links matches the HTTP(S) URL we are signed into. This ensures that the names we use are properly scoped and links generated on one Coder deployment won't accidentally open workspaces on another.
> feat: add check for coder:// URI authority section

- App/Services/MutagenController.cs
- MutagenSdk/MutagenClient.cs
I found the source of the issue where mutagen would fail to acquire the lock on `daemon.lock` at startup.
The MutagenClient attempts to lock the `daemon.lock` file while it is starting, so that it can fail fast if the daemon is not running.
While well meaning, this creates a race condition because as soon as we start the daemon process we create a MutagenClient so that we can talk to the daemon over its API. The MutagenClient might be holding the lock or have the lockfile open at the exact moment the daemon itself attempts to acquire and lock the file. The daemon immediately exits in that case and doesn't retry locking the file.
I've just removed the preflight checks on the `daemon.lock`, since we don't want Coder Desktop to ever mess with that file (outside of tests).
> fix: fix daemon.lock race on mutagen startup

- App/ViewModels/AgentViewModel.cs
- App/ViewModels/TrayWindowViewModel.cs
- App/Views/Pages/TrayWindowMainPage.xaml
- App/Views/Pages/TrayWindowMainPage.xaml.cs
Part 1 of #49
Makes the workspace suffix dynamic in the views. A later PR in this stack will fetch the suffix and apply it to any views if it changes.
If the suffix doesn't match the FQDN provided by the VPN service, we won't gray out anything when we show the name, but if we later get a suffix that matches, it will update.
> chore: make hostname suffix mutable in views

- App/App.xaml.cs
- App/Models/CredentialModel.cs
- App/Services/HostnameSuffixGetter.cs
- App/ViewModels/TrayWindowViewModel.cs
- CoderSdk/Coder/CoderApiClient.cs
- CoderSdk/Coder/WorkspaceAgents.cs
- Tests.App/Services/HostnameSuffixGetterTest.cs
Fixes #49
Adds support to query the hostname suffix from Coder server, and then propagates any changes to the agent view models.
> feat: fetch hostname suffix from API

- App/ViewModels/TrayWindowViewModel.cs
fixes #104
Includes starting, stopping, pending and unknown (rare!) workspaces as "dummy" grayed workspaces.
TBD what we want to do with failed or canceled workspaces.
> fix: change dummy workspace logic to include starting and stopping

- .github/workflows/release.yaml
- Sync fork and submit updated manifest to winget-pkgs.
- Install wingetcreate for submission.
- Fetch git tags to fix lightweight tag issue.
- Comment on PR after submission.
- Use outputs from release job to manage versions.
- Manage installer URLs dynamically for different architectures.
This is adapted from already tested `coder/coder` workflow.
https://github.com/coder/coder/blob/afaa20e1663e773c3f490cba2419ad9217b537f6/.github/workflows/release.yaml#L808-L895
> chore: publish to winget in release workflow

- Installer/Program.cs
- scripts/Publish.ps1
- scripts/files/RtfThemeLarge.xml
Closes: #38 
WiX 5 introduced a bug that stopped respecting the icon file on the theme's Window. This is described in this issue: https://github.com/wixtoolset/issues/issues/8104
This PR introduces:
- an additional option in our `build-bootstrapper` to allow optional setting of the `theme xml`, 
- adds a copy of the `RtfLargeTheme.xml` from WiX `5.0.2` with the added attribute of `IconFile`
> feat: added icon to installer's bootstrap application

- App/App.csproj
Prevents the commit SHA from being included in the "informational version" of the assembly, which is where NetSparkle gets the current version from.
Before:
After:
> chore: hide commit SHA in updater window

- App/App.xaml.cs
- App/Services/UserNotifier.cs
- App/Views/TrayWindow.xaml.cs
> chore: add connect/disconnect notifications on Coder Connect

- Vpn.Service/Manager.cs
The vpn binary doesn't exit by itself on failure to avoid messing up RPC calls, so the parent process is expected to stop it.
> fix: stop vpn binary on startup failure
